#======================================================================
# This demo uses PostgreSQL. This is essentially boilerplate I copy
# from project to project and change the database and user info.
#======================================================================
spring:
  datasource:
    url: jdbc:postgresql://dbserver:5432/demo
    driver-class-name: org.postgresql.Driver
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: trued
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
